cc_library(
    name = "kero_mpsc",
    srcs = [],
    hdrs = ["kero_mpsc.h"],
)

cc_test(
    name = "kero_mpsc_test",
    srcs = ["kero_mpsc_test.cc"],
    deps = [
        ":kero_mpsc",
        "@googletest//:gtest_main",
    ],
)
